name: Report

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

env:
  FROM_EMAIL: ${{ process.env.FROM_EMAIL }}
  FROM_PASSWORD: ${{ process.env.FROM_PASSWORD }}
  TO_EMAIL: ${{ process.env.TO_EMAIL }}

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: pnpm ci

      - run: npx tsx main.ts