name: Report

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

env:
  FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
  FROM_PASSWORD: ${{ secrets.FROM_PASSWORD }}
  TO_EMAIL: ${{ secrets.TO_EMAIL }}
  MONGODB_URI: ${{ secrets.MONODB_URI }}

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 22

      - run: npm install -g pnpm

      - run: pnpm i --frozen-lockfile

      - run: npx tsx main.ts